baseURL = 'https://quentinmoessner.netlify.app'
languageCode = 'fr'
title = 'Moq Website'
enableRobotsTXT = true 

[params]
  googleVerification = 'CM24fE3vRoDVDRo-B6EdXLQ2eEQGwi4FmBg7gI8gR7c'

[markup.goldmark.renderer]
unsafe= true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = false
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4
    